#!/bin/bash

echo "
SET autocommit = 0;
SET default_storage_engine = 'InnoDB';
SET foreign_key_checks = 1;
SET GLOBAL TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET GLOBAL time_zone = '+00:00';
SET SESSION time_zone = '+00:00';

SELECT 'OK';
" | mysql -h localhost -P 3306 -u root --password=12345
