#!/bin/bash

# echo "Please enter the MySQL database password for \"$_MYSQL_HOST:$_MYSQL_PORT@root\""
echo "
SET autocommit = 0;
SET default_storage_engine = 'InnoDB';
SET foreign_key_checks = 1;
SET GLOBAL TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET GLOBAL time_zone = '+00:00';
SET SESSION time_zone = '+00:00';

SELECT 'OK';
" | mysql -h "$_MYSQL_HOST" -P "$_MYSQL_PORT" -u "$_MYSQL_USER" --password="$_MYSQL_PASSWORD"
