#!/bin/bash

sudo rm -rf /var/lib/dpkg/lock &&\
sudo apt-get update &&\
sudo apt-get install -f &&\
sudo apt autoremove &&\

wget https://dev.mysql.com/get/mysql-apt-config_0.8.8-1_all.deb &&\
sudo dpkg -i mysql-apt-config_0.8.8-1_all.deb &&\
sudo rm -rf mysql-apt-config_0.8.8-1_all.deb &&\
sudo apt-get update &&\
sudo apt-get install mysql-server=5.7.* mysql-client=5.7.* libmysqlclient-dev=5.7.* &&\

sudo apt install curl=7.47.* &&\
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - &&\
sudo apt-get update &&\
sudo apt-get install nodejs &&\

sudo add-apt-repository ppa:deadsnakes/ppa &&\
sudo apt-get update &&\
sudo apt-get install python3.6 python3.6-dev python3-pip=8.1.* &&\
sudo apt install libffi-dev=3.2.* &&\ # 'libffi-dev' library for the bcrypt.

sudo python3.6 -m pip3 install --upgrade pip==9.0.1 &&\

# sudo pip install Django==1.11.6 mysqlclient==1.3.12 bcrypt==3.1.4 django-user-sessions==1.5.3
sudo pip install Flask==0.12.2 mysqlclient==1.3.12 PyMySQL==0.7.11 SQLAlchemy==1.1.15
